name: build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/ExpenseTracker

    steps:
    - name: Build server app
      run: cd ./server/ExpenseTracker
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test with the dotnet CLI
      run: dotnet 
    - name: Build client web app
      run: cd ../../clients/web/expense-tracker
    - name: Install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '16.3.x'
    - name: Install packages
      run: npm ci
    - name: Build react app
      run: npm run build
    - name: Test react app
      run: npm run test