name: build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/ExpenseTracker

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test with the dotnet CLI
      run: dotnet test
    - name: Install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '16.3.x'
    - name: Install packages
      working-directory: ./clients/web/expense-tracker
      run: npm ci
    - name: Build react app
      working-directory: ./clients/web/expense-tracker
      run: npm run build
    - name: Test react app
      working-directory: ./clients/web/expense-tracker
      run: npm run test