name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server
      - run: dotnet build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: dotnet test
