name: build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./server/ExpenseTracker
    - name: Build
      run: dotnet build
      working-directory: ./server/ExpenseTracker
    - name: Test with the dotnet CLI
      run: dotnet test
      working-directory: ./server/ExpenseTracker
    - name: Install nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '16.3.x'
    - name: Install packages
      run: pnpm ci
      working-directory: ./clients/web/expense-tracker
    - name: Build react app
      run: pnpm run build
      working-directory: ./clients/web/expense-tracker
    - name: Test react app
      run: pnpm run test
      working-directory: ./clients/web/expense-tracker
